---
- name: Launch instance
  ec2:
    key_name: "{{ key_name }}"
    group: "{{ group }}"
    instance_profile_name: "{{ instance_profile_name }}"
    instance_type: "{{ instance_type }}"
    user_data: "{{ lookup('template', 'templates/user_data.j2') }}"
    image: "{{ image }}"
    wait: true
    wait_timeout: 300
    region: "{{ region }}"
    vpc_subnet_id: "{{ subnet }}"
    assign_public_ip: "{{ assign_public_ip }}"
    count_tag: "{{ name }}"
    exact_count: "{{ instance_count }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: "{{ volume_size }}"
    instance_tags:
      Name: "{{ name }}"
      Environment: "{{ env }}"
      Application: "{{ application }}"
      Component: "{{ component}}"
      Tier: "{{ tier }}"
      Version: "{{ version }}"
      Shutdown: "{{ shutdown }}"
      Owner: "{{ owner }}"
      Creator: "{{ creator }}"
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 5
    timeout: 320
    state: started
  with_items: "{{ ec2.instances }}"
